import "@/app/globals.css";
// import Header from "@/components/Header";
import { NextAuthProvider } from "@/Providers/NextAuthProvider"
// import PreviewPlayer from "@/components/PreviewPlayer";
// import Sidebar from "@/components/Sidebar";
// import TrackPlayerProvider from "@/providers/TrackPlayerProvider";
import { Montserrat } from "next/font/google";
import Sidebar from "../components/Sidebar";
import SpotifyState from "../Context/SpotifyState";
import { getServerSession } from "next-auth";
import Player from "../components/Player";


const fontFamily = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next.js App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}) {

  const session = await getServerSession();

  return (
    <html lang="en">
      <NextAuthProvider session={session}>
        {console.log("ssssss", session)}
        <SpotifyState>
          <body
            className={
              fontFamily.className +
              " h-screen flex flex-col overflow-hidden text-white bg-black items-stretch !p-2"
            }
          >
            <div className="grid grid-cols-12 gap-1">

              <sidebar className="col-span-2 sm:col-span-3">
              <Sidebar />
              </sidebar>

              <div className="flex flex-col h-[87vh] col-span-10 sm:col-span-9 flex-shrink overflow-auto rounded-lg w-full">
                {/* <Header /> */}
                <main className="">{children}</main>
              </div>

              <div className="sticky bottom-0  col-span-12  h-[13vh] bg-black">
               <Player />
            </div>
            </div>
            {/* <PreviewPlayer /> */}
          </body>
          </SpotifyState>
      </NextAuthProvider>
    </html>
  );
}
