import "@/app/globals.css";
// import Header from "@/components/Header";
import { NextAuthProvider } from "@/Providers/NextAuthProvider"
// import PreviewPlayer from "@/components/PreviewPlayer";
// import Sidebar from "@/components/Sidebar";
// import TrackPlayerProvider from "@/providers/TrackPlayerProvider";
import { Montserrat } from "next/font/google";
import Sidebar from "../components/Sidebar";

const fontFamily = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
          <body
            className={
              fontFamily.className +
              " h-screen flex flex-col overflow-hidden text-white bg-black items-stretch !p-2"
            }
          >
            <div className="grid grid-cols-12 gap-1">

              <sidebar className="col-span-2 sm:col-span-3">
              <Sidebar />
              </sidebar>

              <div className="flex flex-col h-[87vh] col-span-10 sm:col-span-9 flex-shrink overflow-auto rounded-lg bg-purple-200 w-full">
                {/* <Header /> */}
                <main className="mx-8 my-4">{children}</main>
              </div>

              <div className="bg-cyan-400 col-span-12  h-[13vh] flex justify-between items-center p-2 ">
                <div className="border-r-2 ">
                  a
                </div>
                <div className="border-r-2 ">
                  a
                </div>
                <div className="border-r-2 ">
                  a</div>  
              </div>
            </div>
            {/* <PreviewPlayer /> */}
          </body>
      </NextAuthProvider>
    </html>
  );
}
